version: "3.8"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 3000:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abcd1234
    volumes:
      - ./database/:/data/db/

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 3003:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: abcd1234
